### ISSUE TITLE
Receiving error after importing .json investigation file. Any help appreciated, thanks!

### ISSUE THREAD

**Issue by stormproof** [wfsec/osxstrata#1]
=> App running at: http://localhost:3000/
I20160321-21:47:31.974(-5)? python /opt/osxstrata/scripts/strata.py -a /opt/osxstrata/scripts/.uploads/tmp/osxcollect-2016_03_21-21_03_03.json
I20160321-21:47:32.664(-5)? { [Error: Command failed: Exception AttributeError: "'Cursor' object has no attribute '_Cursor__id'" in <bound method Cursor.__del__ of <pymongo.cursor.Cursor object at 0x10e60f950>> ignored
I20160321-21:47:32.664(-5)? Traceback (most recent call last):
I20160321-21:47:32.664(-5)?   File "/opt/osxstrata/scripts/strata.py", line 847, in <module>
I20160321-21:47:32.665(-5)?     main()
I20160321-21:47:32.665(-5)?   File "/opt/osxstrata/scripts/strata.py", line 832, in main
I20160321-21:47:32.665(-5)?     analyze(id)
I20160321-21:47:32.665(-5)?   File "/opt/osxstrata/scripts/strata.py", line 188, in analyze
I20160321-21:47:32.665(-5)?     chrome2 = DB.project.find({"osxcollector_section":"chrome","url":{"$exists": 'true'},"url":{"$regex":"http"},"osxcollector_incident_id":id},timeout=False)
I20160321-21:47:32.665(-5)?   File "/Library/Python/2.7/site-packages/pymongo/collection.py", line 1137, in find
I20160321-21:47:32.665(-5)?     return Cursor(self, _args, *_kwargs)
I20160321-21:47:32.665(-5)? TypeError: **init**() got an unexpected keyword argument 'timeout'
I20160321-21:47:32.665(-5)? ] killed: false, code: 1, signal: null } 'FINISHED IMPORT STARTING ANALYSIS... osxcollect-2016_03_21-21_03_03\nANALYSIS\n' 'Exception AttributeError: "\'Cursor\' object has no attribute \'_Cursor__id\'" in <bound method Cursor.__del__ of <pymongo.cursor.Cursor object at 0x10e60f950>> ignored\nTraceback (most recent call last):\n  File "/opt/osxstrata/scripts/strata.py", line 847, in <module>\n    main()\n  File "/opt/osxstrata/scripts/strata.py", line 832, in main\n    analyze(id)\n  File "/opt/osxstrata/scripts/strata.py", line 188, in analyze\n    chrome2 = DB.project.find({"osxcollector_section":"chrome","url":{"$exists": \'true\'},"url":{"$regex":"http"},"osxcollector_incident_id":id},timeout=False)\n  File "/Library/Python/2.7/site-packages/pymongo/collection.py", line 1137, in find\n    return Cursor(self, _args, *_kwargs)\nTypeError: **init**() got an unexpected keyword argument \'timeout\'\n'
I20160321-21:49:37.923(-5)? Exception from sub accounts id gzAczprydfmr2ysHo TypeError: Cannot call method 'split' of null
I20160321-21:49:37.923(-5)?     at sectionQueryBuilder (server/pubs/accounts.js:33:1)
I20160321-21:49:37.923(-5)?     at [object Object]._handler (server/pubs/accounts.js:19:1)
I20160321-21:49:37.923(-5)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160321-21:49:37.923(-5)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20160321-21:49:37.923(-5)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20160321-21:49:37.923(-5)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20160321-21:49:37.923(-5)?     at livedata_server.js:548:43
I20160321-21:49:37.925(-5)? Exception from sub accounts-counter id 24SeaLD7MuJZDMS9Q TypeError: Cannot call method 'split' of null
I20160321-21:49:37.925(-5)?     at sectionQueryBuilder (server/pubs/accounts.js:33:1)
I20160321-21:49:37.925(-5)?     at [object Object]._handler (server/pubs/accounts.js:3:1)
I20160321-21:49:37.925(-5)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160321-21:49:37.925(-5)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20160321-21:49:37.925(-5)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20160321-21:49:37.925(-5)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20160321-21:49:37.925(-5)?     at livedata_server.js:548:43
I20160321-21:49:48.814(-5)? Exception from sub firefox id aGJH6wYrNLM4K55Py Error: Exception while polling query {"collectionName":"project","selector":{"osxcollector_section":"firefox","osxcollector_incident_id":"osxcollect-2016_03_21-21_03_03","$or":[]},"options":{"transform":null,"limit":25,"skip":0}}: Can't canonicalize query: BadValue $and/$or/$nor must be a nonempty array

**Comment by justinlarson** [comment]
What version of pymongo are you using?
